tag

diff --git a/.github/workflows/promote_package.yml b/.github/workflows/promote_package.yml
--- a/.github/workflows/promote_package.yml
+++ b/.github/workflows/promote_package.yml
@@ -1,7 +1,7 @@
 name: Promote Python Package
 
 on:
-  repository_dispatch:      # Triggered by the GitHub repository_dispatch event from Cloudsmith webhook
+  repository_dispatch:      # Trigger via Cloudsmith webhook
     types:
       - package_synchronized
 
@@ -27,19 +27,30 @@ jobs:
           oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
           oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}
 
-      # Step 2: Tag the package with ready-for-production
-      - name: Tag the Synchronised Package
+      # Step 2: Tag the synchronized package with ready-for-production
+      - name: Tag the Synchronized Package
         run: |
           # Extract the package identifier passed in the webhook payload
           IDENTIFIER=${{ github.event.client_payload.package_identifier }}
+          
+          if [ -z "$IDENTIFIER" ]; then
+            echo "Failed to extract package identifier from webhook payload."
+            exit 1
+          fi
+          
           echo "Received Webhook Identifier: $IDENTIFIER"
           
           # Add the ready-for-production tag to the package in the staging repository
           cloudsmith tag add "${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER" "${{ env.PACKAGE_TAG }}"
+          if [ $? -ne 0 ]; then
+            echo "Failed to tag the package with '${{ env.PACKAGE_TAG }}'."
+            exit 1
+          fi
+          
           echo "Package successfully tagged with '${{ env.PACKAGE_TAG }}'."
 
-      # Step 3: Query for all ready-for-production packages and Promote
-      - name: Query Packages and Promote
+      # Step 3: Query for all ready-for-production tagged packages and promote
+      - name: Query Tagged Packages and Promote
         run: |
           # Query for all packages tagged with ready-for-production
           PACKAGE_QUERY="tags:${{ env.PACKAGE_TAG }}"
@@ -59,9 +70,15 @@ jobs:
 
           # Promote each package from staging to production
           for ID in $IDENTIFIERS; do
-            echo "Promoting package: $ID"
             cloudsmith mv --yes \
               ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$ID \
               ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
+            if [ $? -eq 0 ]; then
+              echo "Successfully promoted package: $ID"
+            else
+              echo "Failed to promote package: $ID"
+              exit 1
+            fi
           done
+
           echo "All tagged packages successfully promoted to ${CLOUDSMITH_PRODUCTION_REPO}."
